[package]
name = "storage-proofs-post"
version = "8.0.3"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
license = "MIT OR Apache-2.0"
description = "Proofs of Space Time"
edition = "2018"
repository = "https://github.com/filecoin-project/rust-fil-proofs"
readme = "README.md"

[dependencies]
storage-proofs-core = { path = "../storage-proofs-core", version = "^8.0.0", default-features = false}
filecoin-hashers = { path = "../filecoin-hashers", version = "^3.0.0", default-features = false, features = ["poseidon", "sha256"]}
rand = "0.8"
merkletree = "0.21.0"
byteorder = "1"
crossbeam = "0.8"
sha2 = "0.9.1"
rayon = "1.0.0"
serde = { version = "1.0", features = ["derive"]}
blake2b_simd = "0.5"
blake2s_simd = "0.5"
ff = "0.10.0"
bellperson = { git = "https://github.com/filecoin-project/bellperson", branch = "halo" }
log = "0.4.7"
hex = "0.4.0"
generic-array = "0.14.4"
anyhow = "1.0.23"
neptune = { git = "https://github.com/filecoin-project/neptune", branch = "halo" }
num_cpus = "1.10.1"
fr32 = { path = "../fr32", version = "^1.0.0", default-features = false }

[dev-dependencies]
tempfile = "3"
pretty_assertions = "0.6.1"
rand_xorshift = "0.3.0"
filecoin-hashers = { path = "../filecoin-hashers", version = "^3.0.0", default-features = false, features = ["poseidon", "sha256", "blake2s"]}

[features]
default = ["gpu"]
gpu = ["storage-proofs-core/gpu", "filecoin-hashers/gpu", "fr32/gpu", "neptune/opencl"]
